name: Java CICD with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./server/wonprice

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ env.working-directory }}

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t wonprice . 
          docker tag wonprice jungseow/wonprice:${GITHUB_SHA::7}
          docker push jungseow/wonprice:${GITHUB_SHA::7}
        working-directory: ${{ env.working-directory }}

      - name: SSH Connection and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f wonprice
            sudo docker pull jungseow/wonprice:${GITHUB_SHA::7}
            sudo docker run -d --name wonprice -p 8080:8080 --env-file ./wonprice.env -e "SPRING_PROFILES_ACTIVE=server" jungseow/wonprice:${GITHUB_SHA::7}
